server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#http://120.79.41.196:8761/eureka/
spring:
  application:
    name: shopCommodity
  #\u94FE\u63A5\u6570\u636E\u5E93\u914D\u7F6E
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shao_shop?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
mybatis:
  configuration:
    #\u5F00\u542F\u81EA\u52A8\u9A7C\u5CF0\u547D\u540D\u89C4\u5219\u6620\u5C04
    map-underscore-to-camel-case: true
